alexpasmantier/television

- crates/television/event.rs
> fix(windows): ignore `KeyEventKind::Release` events

- Cargo.lock
- Cargo.toml
- crates/television_channels/Cargo.toml
- crates/television_fuzzy/Cargo.toml
- crates/television_previewers/Cargo.toml
- crates/television_utils/Cargo.toml
> fix(windows): bump television_utils to v0.0.1

- Cargo.lock
- Cargo.toml
- README.md
- crates/television/config.rs
> fix(windows): #20 respect `TELEVISION_CONFIG` env var on windows

- .config/config.toml
- Cargo.lock
- Cargo.toml
- crates/television/config/ui.rs
- crates/television/television.rs
- crates/television/ui/help.rs
- crates/television/ui/layout.rs
> feat(ui): make help bar display optional

- CONTRIBUTING.md
- provide more links to actual files and locations
- add link to crates documentation for newcomers
- add a mention to existing channels
> clarify CONTRIBUTING.md

- Cargo.lock
- Cargo.toml
- README.md
- crates/television-channels/Cargo.toml
- crates/television-channels/src/channels.rs
- crates/television-derive/Cargo.toml
- crates/television-fuzzy/Cargo.toml
- crates/television-previewers/Cargo.toml
- crates/television-utils/Cargo.toml
> fix(cable): add cable to unit channel variants

- crates/television/cli.rs
- crates/television/main.rs
A new CLI arg was added to start tv in another directory:
-d, --working-directory <PATH>
Resolves #111
> Add argument to start tv in another working directory

- .config/config.toml
- crates/television-screen/src/input.rs
- crates/television-screen/src/keybindings.rs
- crates/television-screen/src/layout.rs
- crates/television-screen/src/preview.rs
- crates/television-screen/src/results.rs
- crates/television/action.rs
- crates/television/config/ui.rs
- crates/television/television.rs
> refactor(ui): more compact general layout and make preview panel optional

- .config/config.toml
- crates/television/config.rs
- crates/television/config/keybindings.rs
- crates/television/keymap.rs
- crates/television/television.rs
> feat(config): allow specifying multiple keymaps for the same action + better defaults

- crates/television/action.rs
- crates/television/app.rs
- crates/television/input.rs
- crates/television/television.rs
> feat(input): bind ctrl-w to delete previous word

- crates/television/app.rs
- crates/television/television.rs
> feat(ux): print current query to stdout on Enter if no entry is selected

- crates/television-screen/src/layout.rs
- crates/television/app.rs
- crates/television/cli.rs
- crates/television/main.rs
- crates/television/picker.rs
- crates/television/television.rs
> feat(cli): allow passing --input <STRING> to prefill input prompt

- crates/television-channels/src/channels/text.rs
> fix(channels): use the number of actual bytes read and not the sample buffer size when calculating the proportion of printable ASCII characters

- crates/television/television.rs
> fix(ux): make DeletePrevWord trigger channel update

- .config/config.toml
- crates/television-utils/shell/completion.bash
- crates/television-utils/src/shell.rs
> feat(shell): add bash support for smart autocomplete and shell history

- .config/config.toml
- crates/television-previewers/src/previewers/files.rs
> feat(ui): respect BAT_THEME env var for previewer syntax highlighting theme

- flake.nix
Hey! Quick fix for nix, already tested on my machine, works like a charm!
> fix build on nix

- cable/unix-channels.toml
- cable/windows-channels.toml
> refactor(shell): use $HISTFILE for cable history channels

- crates/television/cable.rs
> refactor(cable): always create default cable channels in user directory if no cable channels exist

- crates/television-screen/src/colors.rs
- crates/television-screen/src/help.rs
- crates/television-screen/src/input.rs
- crates/television-screen/src/preview.rs
- crates/television-screen/src/remote_control.rs
- crates/television-screen/src/results.rs
- crates/television/config/themes.rs
> feat(ui): make background color optional and fallback to terminal default bg color

- crates/television-channels/src/channels/dirs.rs
- crates/television-channels/src/channels/files.rs
- crates/television-channels/src/channels/text.rs
> feat(channels): allow sending currently selected entries to other channels

- crates/television-utils/src/strings.rs
> feat: add support for CJK unified ideographs

- crates/television/cli.rs
- crates/television/main.rs
> feat(cli): add `no-preview` flag to disable the preview pane

- README.md
Makes the library a bit more discoverable, great to see it in use!
> Link to nucleo directly

- .config/config.toml
- crates/television/event.rs
> refactor: exit application on SIGINT / C-c

- crates/television/cli.rs
> fix(cable): cable channels now take precedence over builtins for the cli / shell integration

- Cargo.lock
- Cargo.toml
- crates/television-previewers/src/previewers/files.rs
- crates/television-utils/Cargo.toml
- crates/television-utils/src/syntax.rs
> fix(syntect): switch back to oniguruma while investigating parsing issues

- crates/television-utils/src/strings.rs
This PR adds
- support for katakana and hiragana
- support for hangul
- support for thai
- support for devanagari
- support for emojis
Some special characters such as typographic parentheses for the Japanese language for example don't seem to be covered by the Unicode ranges I'm adding in this pull request.
To ensure complete support, additional Unicode ranges should be added by native speakers when possible to avoid errors.
Fixes #299
> feat(i18n): improve support for non-western scripts

- Cargo.lock
- Cargo.toml
> fix(cli): re-enable clap help feature

- television/config/mod.rs
- television/config/shell_integration.rs
> fix(config): add serde default for shell integration configuration

- .config/config.toml
- Cargo.lock
- Cargo.toml
- benches/main/draw.rs
- television/config/mod.rs
- television/config/previewers.rs
- television/config/shell_integration.rs
- television/main.rs
- television/screen/layout.rs
- television/utils/hashmaps.rs
- television/utils/mod.rs
Before:
```toml
[shell_integration.commands]
#
"export" = "env"
"unset" = "env"
"cd" = "dirs"
"ls" = "dirs"
"rmdir" = "dirs"
"cat" = "files"
"less" = "files"
"head" = "files"
"tail" = "files"
"vim" = "files"
"bat" = "files"
"git add" = "git-diff"
"git checkout" = "git-branch"
"git branch -d" = "git-branch"
"docker run" = "docker-images"
"nvim" = "git-repos"
```
After
```toml
[shell_integration.channel_triggers]
#
"env" = ["export", "unset"]
"dirs" = ["cd", "ls", "rmdir"]
"files" = ["cat", "less", "head", "tail", "vim", "bat"]
"git-diff" = ["git add"]
"git-branch" = ["git checkout", "git branch -d"]
"docker-images" = ["docker run"]
"git-repos" = ["nvim"]
```
> refactor(shell): improve shell integration configuration syntax

- television/channels/cable.rs
- television/channels/mod.rs
- television/draw.rs
- television/screen/help.rs
- television/screen/input.rs
- television/screen/metadata.rs
- television/television.rs
> refactor(ui): display current channel in input bar border

- television/app.rs
> fix(events): remove sorting and deduplicating incoming actions

- cable/unix-channels.toml
> refactor(cable): use HISTFILE for bash and zsh history channels

- .github/workflows/cd.yml
> ci(deb): fix cargo deb output directory error

- .github/workflows/cd.yml
- Cargo.lock
- Cargo.toml
- build.rs
- man/tv.1
- television/cli/args.rs
- television/cli/mod.rs
- television/main.rs
> docs(man): add man pages for tv

- television-derive/src/lib.rs
- television/channels/alias.rs
- television/channels/cable.rs
- television/channels/dirs.rs
- television/channels/env.rs
- television/channels/files.rs
- television/channels/git_repos.rs
- television/channels/mod.rs
- television/channels/remote_control.rs
- television/channels/stdin.rs
- television/channels/text.rs
- television/draw.rs
- television/preview/mod.rs
- television/render.rs
- television/television.rs
- television/utils/metadata.rs
> refactor(startup): improve overall startup time and remove first frames artifacts

- man/tv.1
- television/app.rs
- television/cli/args.rs
- television/cli/mod.rs
- television/config/mod.rs
- television/main.rs
> feat(cli): allow passing custom keybindings through the cli

- television/app.rs
> feat(config): allow remapping input builtin keybindings (ctrl-e, ctrl-a, etc.)

- .github/workflows/cd.yml
> chore: add support for arm64 deb releases

- .config/config.toml
- television/cli/mod.rs
- television/config/mod.rs
- television/config/shell_integration.rs
- television/event.rs
- television/main.rs
> feat(shell): add fallback channel to the config for smart autocomplete

- television/config/mod.rs
> fix(config): make user shell integration trigger configuration override defaults entirely

- television/draw.rs
- television/screen/results.rs
> fix(ui): show preview toggle hint conditionally

- television/config/mod.rs
- television/main.rs
> fix(config): fix shell integration keybindings not overwriting defaults

- benches/main/draw_results_list.rs
- television/screen/remote_control.rs
- television/screen/results.rs
- television/television.rs
- television/utils/indices.rs
> refactor: nicer results alignment to improve discoverability of matched patterns

- benches/main/draw.rs
- benches/main/draw_results_list.rs
- television/channels/alias.rs
- television/channels/cable.rs
- television/channels/dirs.rs
- television/channels/entry.rs
- television/channels/env.rs
- television/channels/files.rs
- television/channels/git_repos.rs
- television/channels/remote_control.rs
- television/channels/stdin.rs
- television/channels/text.rs
- television/matcher/matched_item.rs
- television/matcher/mod.rs
- television/screen/colors.rs
- television/screen/results.rs
- television/utils/indices.rs
- television/utils/strings.rs
> fix(results): fix alignment for non unit width unicode characters

- cable/windows-channels.toml
- television/channels/alias.rs
- television/channels/cable.rs
- television/preview/previewers/command.rs
- television/utils/command.rs
- television/utils/shell.rs
> fix(pwsh): use adequate quoting when formatting preview commands for pwsh

- television/television.rs
We were drawing an excessive amount of frames while any channel was in its `running` state which resulted in rendering operations monopolizing CPU resources thus making the application appear less responsive to the user.
Fixes #459
> fix(ui): fix slight responsiveness regression in 0.11.6

- television/render.rs
This adds quite a nice bump to overall UI reactiveness.
> perf(ui): add frame rate throttling to avoid consuming unnecessary CPU resources

- television/config/ui.rs
- television/draw.rs
- television/screen/results.rs
- television/television.rs
> fix(results): remove keymap hint if help is disabled

- television/cable.rs
The cable channel prototypes are now compiled into the binary itself, and users can override them with a custom cable file.
> refactor: tv no longer needs to write the default cable channel recipes to the user's configuration directory

- television/utils/shell/completion.zsh
Fixes https://github.com/alexpasmantier/television/issues/393
> fix(shell): Paste not working in zsh shell integration

- cable/windows-channels.toml
- television/channels/cable.rs
> feat(windows): add text channel with preview offset for windows

- benches/main/ui.rs
- television/channels/prototypes.rs
- television/cli/mod.rs
- television/main.rs
- tests/app.rs
> fix(config): use the config `default_channel` field as a fallback when no channel is specified

- benches/main/ui.rs
- cable/unix/files.toml
- television/action.rs
- television/app.rs
- television/channels/prototypes.rs
- television/cli/args.rs
- television/cli/mod.rs
- television/config/mod.rs
- television/config/ui.rs
- television/main.rs
- television/screen/layout.rs
- television/television.rs
- tests/app.rs
This PR gives support to define multiple preview sizes and to toggle them at will
> Preview size customization

- television/channels/channel.rs
- television/television.rs
> fix(reload): avoid UI flickering while reloading channel

- cable/unix/git-repos.toml
- television/channels/channel.rs
- television/channels/prototypes.rs
- television/cli/args.rs
- television/cli/mod.rs
- television/main.rs
> feat(stdin): accept various entry separator characters

- television/config/keybindings.rs
> fix(keybindings): add cmd as an option for modifrs

- docs/cli.md
- man/tv.1
- television/app.rs
- television/cli/args.rs
- television/cli/mod.rs
- television/errors.rs
- television/main.rs
- television/render.rs
- television/tui.rs
- tests/app.rs
> Adds support for non-fullscreen interfaces

- television/channels/prototypes.rs
- television/main.rs
- television/screen/status_bar.rs
- Improved determine channel logic, it will make easier to maintain moving forward
- Fixed hint logic for preview, it had issues for stdin and ad-hoc channels
- Override logic for CLI UI elements was not handled consistently
- Added few more tests
> Minor changes

- television/tui.rs
Fixes #617 
Cursor position is now correctly set regardless of the layout
> fix(tui): better handling of cursor position

- television/config/themes.rs
Fixes https://github.com/alexpasmantier/television/issues/603.
Regarding the 2nd point of [your comment](https://github.com/alexpasmantier/television/issues/603#issuecomment-3048772061), @alexpasmantier:
> - display a custom error message instead of panicking when themes, **configuration** and **channels** encounter a parsing error
I couldn't find anything specific for other configuration or channels regarding parsing errors, they're already properly handled it seems. Although there's a high chance I might've missed something. Please do let me know if I did.
> fix(themes): make channel mode background optional

- justfile
- television/utils/shell/README.md
- television/utils/shell/completion.fish
- television/utils/shell/completion.nu
> fix(nushell): append to existing nu keybindings instead of replacing them

- README.md
Added a Discord server badge to the README file that links to the community Discord server.
> feat: add discord server badge in README file

- .gitignore
- tests/cli/cli_config.rs
- tests/cli/cli_input.rs
- tests/cli/cli_monitoring.rs
- tests/cli/cli_ui_behavior.rs
- tests/common/mod.rs
update all file based tests to follow a naming convention in a dedicated testing folder to prevent clashes. Make sure all needed files are in place before running the test
> tests: make file based testing more robust with unique identifiers

- .github/workflows/cd.yml
> ci: fix aarch64-linux-gnu cross compilation

- docs/01-Users/01-installation.md
- install.sh
- website/static/install.sh
```bash
curl -fsSL https://alexpasmantier.github.io/television/install.sh | bash
```
> feat: installation script

- docs/01-Users/04-keybindings.md
Update docs to reflect the current default keybindings.
> docs: update default keybindings
