Cargo.lock, Cargo.toml, crates/television_utils/Cargo.toml
I noticed the `bat` dependency was grabbed as-is, which includes a lot of features and transitive dependencies unnecessary when using it in library mode.
This hopefully cleans this up (there's a noticeable drop in `Cargo.lock` entries)
=> chore(deps): disable bat dependency application features

crates/television-channels/src/channels/stdin.rs
Split into two commits:
- Display stdin top-down instead of bottom-up. This makes using television for browsing shell history more intuitive.
- Makes a change to skip empty or whitespace-only lines from showing up. I am not entirely sure this is a good idea especially that it `trim()`s the lines, which may not be what the user wants for very specific use cases. Feel free to skip this commit of course.
=> Display stdin more intuitively top-down instead of bottom-up

crates/television-channels/src/entry.rs
=> fix: shell quote file names that contain spaces when printing them to stdout

README.md
Hey, thanks for starting this amazing project! I added `television` to [`conda-forge`](https://github.com/conda-forge/television-feedstock) to facilitate an easy install on all platforms. If you want we can add the install example to the readme.
=> add `conda-forge` install to README.md

crates/television-channels/src/channels/alias.rs, crates/television-channels/src/channels/env.rs, crates/television-channels/src/channels/git_repos.rs, crates/television-channels/src/channels/remote_control.rs, crates/television-channels/src/channels/text.rs, crates/television-previewers/src/previewers/cache.rs, crates/television-previewers/src/previewers/directory.rs, crates/television-previewers/src/previewers/files.rs, crates/television/app.rs, crates/television/config.rs, crates/television/config/previewers.rs, crates/television/event.rs, crates/television/television.rs
this PR removes a bunch of redundant calls to `.clone()` 
the list was obtained by running 
```
cargo clippy -- -W clippy::redundant_clone
``` 
on the source and removing the associated calls
- I ran `cargo test` to ensure tests are still OK
- I ran `cargo build --release` to rebuild the app and used it without any issue
=> remove unnecessary clone() calls

crates/television/ui/help.rs, crates/television/ui/results.rs
this PR replaces straight colors by named constants, which should facilitate any subsequent move to refactor the theming capabilities of `tv`
=> chore: use named constant for colors

crates/television-channels/src/channels/cable.rs, crates/television-previewers/src/previewers/command.rs, crates/television-utils/src/command.rs, crates/television-utils/src/lib.rs
use `cmd` to execute command on windows, otherwise the following error occurs.
```
name = "television"
operating_system = "Windows 10.0.26100 (Windows 11 CoreCountrySpecific) [64-bit]"
crate_version = "0.6.0"
explanation = '''
Panic occurred in file 'D:\env\rust\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\television-previewers-0.0.8\src\previewers\command.rs' at line 158
'''
cause = 'failed to execute process: Error { kind: NotFound, message: "program not found" }'
method = "Panic"
backtrace = """
0:     0x7ff6488deb0b - onig_get_start_by_callout_args
1:     0x7ff6488df9f0 - onig_get_start_by_callout_args
2:     0x7ff6489eea33 - onig_get_start_by_callout_args
3:     0x7ff6489f1317 - onig_get_start_by_callout_args
4:     0x7ff648d70710 - onig_get_start_by_callout_args
5: …
```
=> fix(windows): use cmd on windows instead of sh

crates/television-channels/src/entry.rs
in the entries that are used in the `build_results_list` function in `television-screen::results`, it seems like there the ranges returned are sometimes contiguous
since they're used to create `ratatui` spans, we want to reduce them to their minimal equivalent form
=> perf: merge contiguous name match ranges

crates/television-channels/src/entry.rs, crates/television-screen/src/results.rs
```
results_list            time:   [17.800 µs 17.836 µs 17.869 µs]
change: [-0.7235% -0.4176% -0.1185%] (p = 0.01 < 0.05)
Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
3 (3.00%) high mild
```
```
results_list            time:   [12.780 µs 12.789 µs 12.798 µs]
change: [-28.381% -28.218% -28.059%] (p = 0.00 < 0.05)
Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
1 (1.00%) high mild
4 (4.00%) high severe
```
=> perf(ui): improve merging of continuous name match ranges

benches/results_list_benchmark.rs, crates/television-channels/src/entry.rs, crates/television-screen/src/results.rs
```
results_list            time:   [12.175 µs 12.195 µs 12.217 µs]
change: [-1.7157% -0.9562% -0.4063%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 28 outliers among 100 measurements (28.00%)
5 (5.00%) low severe
14 (14.00%) low mild
4 (4.00%) high mild
5 (5.00%) high severe
```
```
results_list            time:   [11.671 µs 11.772 µs 11.923 µs]
change: [-3.9850% -3.5914% -3.1779%] (p = 0.00 < 0.05)
Performance has improved.
Found 28 outliers among 100 measurements (28.00%)
22 (22.00%) low severe
6 (6.00%) high severe
```
=> perf: optimize entry ranges

.config/config.toml, README.md, benches/results_list_benchmark.rs, crates/television-screen/src/colors.rs, crates/television-screen/src/help.rs, crates/television-screen/src/input.rs, crates/television-screen/src/keybindings.rs, crates/television-screen/src/metadata.rs, crates/television-screen/src/mode.rs, crates/television-screen/src/preview.rs, crates/television-screen/src/remote_control.rs, crates/television-screen/src/results.rs, crates/television/app.rs, crates/television/config.rs, crates/television/config/previewers.rs, crates/television/config/themes.rs, crates/television/config/themes/builtin.rs, crates/television/config/ui.rs, crates/television/television.rs, themes/catppuccin.toml, themes/gruvbox-dark.toml, themes/nord.toml, themes/solarized-dark.toml
fixes #80 
| gruvbox | solarized |
| :-: | :-: |
| <img width="1792" alt="gruvbox" src="https://github.com/user-attachments/assets/c0c168a5-5c95-4113-93fd-24b34a9344d8" /> | ![Screenshot 2024-12-13 at 14 38 57](https://github.com/user-attachments/assets/368e3e37-7fdd-493a-8c0b-47e3731ae67b) |
=> feat(themes): add support for ui themes

README.md
I made this PR following some confusion I had as a first time user reading the documentation. I tried GitRepos, git-repos and finally had to call list-channels to find the actual name for gitrepos. I think making all of the references to channels consistent with the spelling/capitalization of the CLI helps reduce confusion.
=> docs(readme): make channel names consistent everywhere

.config/config.toml, crates/television-screen/src/layout.rs, crates/television/config/ui.rs, crates/television/television.rs
fixes #143 
```toml
[ui]
input_bar_position = "top"
preview_title_position = "top"
```
=> feat(ui): decouple preview title position from input bar position and make it configurable

Cargo.lock, Cargo.toml
👋 seeing some version mismatch with the release build. 
relates to https://github.com/Homebrew/homebrew-core/pull/202798
=> fix: bump version to match with the release

Cargo.toml
Fixes #185 
> Release + codegen-units = 1: 11 Mib
Release + Thin LTO (current default): 14 Mib
Release + Fat LTO: 11 Mib
Release + codegen-units = 1 + Fat LTO: 9.7 Mib
Release + codegen-units = 1 + Thin LTO: 11 Mib
=> perf(bin): compile binary as a single code unit and use fat LTO

crates/television-derive/src/lib.rs
```
tv gitrepos
Unknown channel: gitrepos
```
And `tv list-channels` result, before the fix:
```
tv list-channels
Builtin channels:
env
files
gitrepos
dirs
text
alias
```
After:
```
./target/debug/tv list-channels
Builtin channels:
env
files
git-repos // HERE
dirs
text
alias
```
=> fix(channels): list-channels in kebab-case

README.md
the sections for _keybindings_, the _configuration file_ and _search patterns_ are now located in dedicated pages of the Wiki and referred to in the README
=> docs: move parts of README to Wiki

crates/television/config.rs
I've noticed that the latest release (0.85.0) failed to start up if `$HOME/.config/television` doesnt exist. This should force the directory creation if the user doesn't have it.
Before:
After:
=> fix: automatically create configuration directory if it doesnt exist

README.md
=> Fix broken link to autocompletion docs

cable/unix-channels.toml
=> fix(unix): use sed instead of tail for bash and zsh default history channels

.config/config.toml, crates/television/config/themes.rs, crates/television/config/themes/builtin.rs, themes/default.toml
=> feat(ui): add support for standard ANSI colors theming and update default theme

crates/television-channels/src/channels/alias.rs, crates/television-channels/src/channels/cable.rs, crates/television-previewers/src/previewers/command.rs
=> fix(ingestion): use lossy conversion when source doesn't produce valid utf8

crates/television-channels/src/channels/cable.rs
=> perf: drop deduplication when loading cable candidate lines

crates/television-channels/src/channels/cable.rs
=> fix(cable): filter out non-utf8 lines when loading cable candidates

crates/television-utils/src/strings.rs
=> feat(preview): add support for displaying nerd fonts in preview

.github/workflows/cd.yml
Resolves GH-296 without replacing current tar.gz for backward compatibility
I have tested with similar code, then the workflow uploads files like https://github.com/kachick/television/releases/tag/0.999.999
=> chore: add zip format in a Windows release assets

crates/television-utils/shell/completion.fish
The call ensures that the prompt restores properly and looks correct after using television. This fixes #300 for me locally.
=> fix: Add repaint command to the fish shell scripts

television/app.rs, television/channels/alias.rs, television/channels/cable.rs, television/channels/entry.rs, television/channels/git_repos.rs, television/channels/remote_control.rs, television/channels/stdin.rs, television/television.rs
fixes #284
the outcome of entry selection quoting was not consistent depending on whether the entry existed on the filesystem or not
this PR removes all entry quoting, making the behaviour consistent and predictible
- remove quoting of entries in Entry#stdout_repr
- apply clippy suggestions for redundant clones
=> fix(stdout): never quote selected entries

.config/config.toml, television/config/mod.rs, television/config/shell_integration.rs, television/main.rs, television/utils/shell.rs, television/utils/shell/completion.bash, television/utils/shell/completion.fish, television/utils/shell/completion.zsh
- allow custom keybindings through configuration
- this only works for `ctrl-xxx` keybindings for now (using anything else in the configuration will make `tv` fall back to `ctrl-t` and `ctrl-r`
Fixes #268
=> chore(terminal): custom shell keybindings

.github/dependabot.yml, .github/workflows/winget.yml
Resolves #332
ref: https://github.com/microsoft/winget-pkgs/pull/220105, #298
I have added the [winget section in wiki](https://github.com/alexpasmantier/television/wiki/Installation/_compare/2e18237501fab83f8428244c81055c0a4a09dcf8...5695e45a363239f0889d371d949029803f3077af).
This PR aims to keep latest version in the winget-pkgs.
[This action](https://github.com/vedantmgoyal9/winget-releaser) is widely used for this purpose.
- https://github.com/sharkdp/fd/blob/3a56c32a1c661c2cf615d6936b3032fcedc6faff/.github/workflows/CICD.yml#L261
- https://github.com/junegunn/fzf/blob/bbe1721a1883426f639c1efe6afef1d3e6c25181/.github/workflows/winget.yml#L10
However I couldn't test this action in my environment. Could you test after registering the secret?
Feel free to modify the code and/or secret …
=> chore(cd): automatically bump winget-pkgs registered version

television/tui.rs
=> fix(windows): bypass mouse capture disabling on windows

television/television.rs
=> fix(clipboard): gracefully fail if clipboard isn't available

flake.nix
Hey again, just realized there was an update with toolchain change 1.81 -> 1.83, so updating the hash for it :)
=> update rust toolchain hash

Cargo.lock, Cargo.toml, television/main.rs, television/television.rs, television/utils/clipboard.rs, television/utils/mod.rs, television/utils/rocell.rs
fixes #282 
tested with the following setup:
```
-`                    alex@alex-mbp
.o+`                   -------------
`ooo/                   OS: Arch Linux x86_64
`+oooo:                  Host: MacBookPro10,2 1.0
`+oooooo:                 Kernel: 6.13.3-arch1-1
-+oooooo+:                Uptime: 1 hour, 8 mins
`/:-:++oooo+:               Packages: 559 (pacman)
`/++++/+++++++:              Shell: zsh 5.9
`/++++++++++++++:             Resolution: 2048x1280
`/+++ooooooooooooo/`           WM: awesome
./ooosssso++osssssso+`          Theme: Adwaita [GTK3]
.oossssso-````/ossssss+`         Icons: Adwaita [GTK3]
-osssssso.      :ssssssso.        Terminal: tmux
:osssssss/        osssso+++.       CPU: Intel i5-3230M (4) @ 3.200GHz
/ossssssss/        +ssssooo/-       GPU: Intel 3rd Gen Core …
=> fix(clipboard): fix issue where clipboard wouldn't work on X11-based environments

television/config/keybindings.rs, television/config/shell_integration.rs
=> feat(shell): allow mapping ctrl-space for builtin shell autocomplete integration

docs/channels.md
The channel git-repos was listed as gitrepos which made me think it was not working.
=> Corrected git-repos name in channels.md

television/utils/shell/completion.zsh
Problem: The `_tv_shell_history` command does not include the most recent entries in that shell's history.
It uses the `zsh-history` channel, but that's flawed because only the current shell knows its most recent history; it has not yet been written to `$HISTFILE`.
Instead, take input from the shell's history command.
=> fix(zsh): use history command to include recent entries

television/channels/cable.rs, television/channels/stdin.rs, television/cli/mod.rs, television/main.rs, television/utils/shell.rs
=> feat(cli): allow passing builtin previewers through the cli (e.g. `--preview ':files:'`)

.config/config.toml, television/app.rs, television/config/keybindings.rs, television/config/mod.rs, television/draw.rs, television/keymap.rs, television/screen/keybindings.rs
BREAKING CHANGE: mode keybindings dropped in favor of a global table
**What this means in practice:**
```toml
[keybindings.Channel]
quit = ["esc", "ctrl-c"]
[keybindings.RemoteControl]
quit = ["esc", "ctrl-c"]
[keybindings.SendToChannel]
quit = ["esc", "ctrl-c"]
```
are being replaced with
```toml
[keybindings]
quit = ["esc", "ctrl-c"]
```
Mode keybindings were I believe a premature optimization which only brought additional complexity and redundancy to the code and did not provide any real functionality in the current state of things for end users.
=> refactor(config)!: simplify keybindings configuration syntax

.github/workflows/cd.yml
Fixes #339 
```
$ ldd target/x86_64-unknown-linux-musl/release/tv
statically linked
```
=> ci(x86): add statically linked musl build for x86_64

television/action.rs, television/app.rs, television/cli/args.rs, television/cli/mod.rs, television/main.rs, tests/app.rs
BREAKING CHANGE: the CLI `passthrough_keybindings` are no longer available. This feature wasn't used anywhere to my knowledge (github search) and was adding unnecessary complexity to the code.
=> refactor(passthrough)!: drop support for unused passthrough keybindings

man/tv.1, television/app.rs, television/channels/alias.rs, television/channels/cable.rs, television/channels/dirs.rs, television/channels/files.rs, television/channels/git_repos.rs, television/channels/stdin.rs, television/channels/text.rs, television/cli/args.rs, television/cli/mod.rs, television/main.rs, television/matcher/mod.rs, tests/app.rs
Adds a `--select-1` flag that enables `tv` to automatically select the
only result and exit when such a case appears.
Fixes #440
=> feat(cli): add `--select-1` cli flag to automatically select unique result

television/utils/shell/completion.fish
The `string match` statement outputs strings if they match, so the `tv_smart_autocomplete` function was doing this if I invoke it with `'cd '` on my command line
It outputs `cd ` (in the first line) since the `$current_prompt` successfully matches (cause it ends with a space).
Let's fix this by making the `string match` silent with `-q`.
=> fix: silence the `string match` in tv_smart_autocomplete

television/app.rs, television/cli/args.rs, television/cli/mod.rs, television/main.rs, television/television.rs, tests/app.rs
This will disable the remote control panel and associated actions entirely. This is useful when the remote control is not needed or when the user wants `tv` to run in single-channel mode (e.g. when using it as a file picker for a script or embedding it in a larger application).
=> feat(cli): add a `--no-remote` flag to lock the application on the cli-invoked channel

benches/main/draw.rs, television/app.rs, television/cli/args.rs, television/cli/mod.rs, television/config/mod.rs, television/main.rs, television/television.rs, tests/app.rs
This will disable the help panel and associated toggling actions
entirely. This is useful when the help panel is not needed or
when the user wants `tv` to run with a minimal interface (e.g. when
using it as a file picker for a script or embedding it in a larger
application).
=> feat(cli): add a `--no-help` flag to allow disabling showing the help panel

television/utils/shell/completion.bash, television/utils/shell/completion.fish, television/utils/shell/completion.zsh
I think it's better to insert our output at the cursor so this can be invoked in the middle of a prompt. Previously we would assume the cursor is at the end of the prompt and invocation in the middle of one would discard everything after the cursor.
=> feat(shell): support completion in the middle of a prompt

television/action.rs, television/app.rs, television/input.rs, television/television.rs
This is hard-coded to be bound to <kbd>C-u</kbd> by default.
With tv's default keybindings configuration, this is overriden by `scroll_preview_half_page_up` which means users will need to bind that to something else in order to "unlock" that delete-line functionality.
=> feat(input): add action to delete input line

benches/main/ui.rs, television/cable.rs, television/channels/cable.rs, television/channels/cable/preview.rs, television/channels/cable/prototypes.rs, television/channels/remote_control.rs, television/cli/mod.rs, television/main.rs, tests/app.rs
This refactors `television/channels/cable.rs` into two additional submodules:
- `television/channels/cable/preview.rs`
- `television/channels/cable/prototypes.rs`
=> refactor(cable): split cable related code into separate submodules

television/utils/shell/completion.nu
I've updated the completion.nu script to use nushell syntax. I tested this with a custom cable channel and placed the keybinding logic directly within completion.nu. Next steps will mean figuring out how to move that logic into, I think, shell.rs.
=> Updating for nushell syntax

television/utils/shell/completion.fish
this pr adds the possibility of starting television from a different directory and it gives the option of complete a partial match. For example
```fish
cd ~/.config/<ctrl-t>    # opens television at '~/.config/' with an empty search bar
cd ~/.config/fi<ctrl-t>    # opens television at '~/.config/' with 'fi' in the search bar
```
solves (for fish shell) https://github.com/alexpasmantier/television/issues/438
=> feat(shell): improve fish completion system

.config/config.toml, television/config/ui.rs, television/draw.rs, television/screen/input.rs, television/screen/layout.rs
Fixes #489 
This PR adds support for television orientation, input_bar_position is preserved and activating/deactivating the preview works for both :
1. Landscape (default orientation)
a. input_bar_position = "top"
b. input_bar_position = "bottom"
2. Portrait (new orientation)
a. input_bar_position = "top"
b. input_bar_position = "bottom"
=> feat(orientation): add orientation for television #489

television/app.rs
=> feat(remote): redirect `Action::Quit` to `Action::ToggleRemoteControl` when in remote mode

benches/main/ui.rs, cable/unix-channels.toml, cable/windows-channels.toml, television/app.rs, television/cable.rs, television/channels/cable.rs, television/channels/preview.rs, television/channels/prototypes.rs, television/cli/args.rs, television/cli/mod.rs, television/config/mod.rs, television/main.rs, television/previewer/state.rs, television/screen/preview.rs, television/television.rs, tests/app.rs
BREAKING CHANGE: the format of the cable channel files and more specifically the preview specification is updated to be a single table named `preview` (with keys `command`, `delimiter`, and `offset`) instead of three flat fields.
```toml
preview_command = "echo 3"
preview_delimiter = " "
preview_offset = "{1}"
```
becomes: 
```toml
preview.command = "echo 3"
preview.delimiter = " "
preview.offset = "{1}"
```
=> refactor!(cable): update cable channel preview configuration format + add custom preview offsets

cable/unix/env.toml, cable/unix/files.toml, television/action.rs, television/channels/channel.rs, television/channels/prototypes.rs, television/cli/mod.rs, television/config/keybindings.rs, television/draw.rs, television/main.rs, television/matcher/mod.rs, television/previewer/mod.rs, television/screen/help.rs, television/screen/keybindings.rs, television/screen/metadata.rs, television/television.rs
Add env channel
Add support to toggle between sources and reload them, this enables the following
```toml
[source]
command = ["fd -t f", "fd -t f -H"]
[keybindings]
toggle_source = "ctrl-t"
reload_source = "ctrl-r"
```
now you can have the same channel with two different representations, for example with and without hidden files
the change is backwards compatible, if you put a simple string nothing changes
=> New channel and added reload and toggle actions

television/channels/channel.rs, television/channels/remote_control.rs, television/matcher/config.rs, television/matcher/injector.rs, television/matcher/mod.rs, television/picker.rs, television/screen/result_item.rs, television/television.rs, television/utils/strings.rs
before
```
on   ➜ cargo bench --bench main -- --save-baseline before
Finished `bench` profile [optimized] target(s) in 0.13s
Running benches/main.rs (target/release/deps/main-8151fda9d09b6257)
results_list            time:   [16.002 µs 16.095 µs 16.190 µs]
Found 3 outliers among 100 measurements (3.00%)
1 (1.00%) low mild
2 (2.00%) high mild
Benchmarking draw: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.6s, or reduce sample count to 80.
draw                    time:   [2.0829 ms 2.2517 ms 2.4277 ms]
```
after
```
on   ➜ cargo bench --bench main -- --baseline before
Finished `bench` profile [optimized] target(s) in 0.08s
Running benches/main.rs (target/release/deps/main-8151fda9d09b6257)
results_list            time: …
```
=> perf: optimization of the hot paths

television/app.rs, television/cable.rs, television/matcher/mod.rs, television/television.rs
before
after
ran with this command
```
cargo flamegraph --no-inline -c 'record -F 997 --call-graph dwarf --no-inherit' --profile=profiling -- --cable-dir ./cable --config-file ./.config/config.toml files ~/
```
=> perf: pre-allocate result vectors, and reuse picker entries to avoid reallocations

.config/config.toml, television/app.rs, television/config/keybindings.rs, television/config/mod.rs, television/config/ui.rs, television/draw.rs, television/event.rs, television/screen/preview.rs, television/tui.rs
cleaned up keybinding section from config
@alexpasmantier you had this code before, perhaps there was a reason for it?
```rust
if cfg!(not(windows)) {
execute!(buffered_stderr, DisableMouseCapture)?;
}
```
=> UI: Optional scrollbar and mouse support for the preview panel

television/television.rs
Before running tv like so:
tv text dir_name --exact --input query
would fuzzysearch on the "query" word.
Now it respects the matching mode.
=> using --exact now works on the --input text aswell

television/errors.rs, television/render.rs, television/tui.rs, tests/cli/cli_ui.rs
=> refactor: more stable behavior for `--inline`, `--width` and `--height`

television/app.rs, television/channels/entry.rs, television/errors.rs, television/main.rs, television/render.rs, television/tui.rs, television/utils/input.rs, television/utils/shell/completion.bash, television/utils/shell/completion.fish, television/utils/shell/completion.nu, television/utils/shell/completion.zsh
=> fix(tui): fixed shell completion widget not rendering, add poc for fish

cable/unix/nu-history.toml, cable/windows/nu-history.toml, television/tui.rs, television/utils/shell/completion.nu
Fixes #592 
-  Left of cursor extraction - lhs
- Right of cursor extraction - rhs
- Add space if needed - lhs_with_space
- Concatenate lhs + output + rhs - new_line
- Set line and cursor position - command line edit --replace and command line set-cursor
- add nu-history for both windows and unix channels
- [X ] my commits **and PR title** follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) format
=> fix (shell) : nu shell integration enhancement

television/utils/shell/completion.fish
When I set up the keybinds for my fish, I couldn't configure them. After a while, I realized that there are two modes for fish. Whenever vim mode is set up for fish with `fish_vi_key_bindings`.
Based on how the keybinds are set in [fzf.fish](https://github.com/PatrickF1/fzf.fish/blob/8920367cf85eee5218cc25a11e209d46e2591e7a/functions/fzf_configure_bindings.fish#L32), I managed to fix it.
Let me know what you think 🤞
=> fix: set fish keybinds for both default and insert modes

television/tui.rs
Fixes #615 
When we want to draw a viewport of `required_height` lines, we need
- required_height -> the lines that belong to the TUI
- 1 -> the cursor’s own line (top border of the viewport)
A few lines later we compute how many rows to scroll:
The extra - 1 deliberately discounts the cursor’s current line (we don’t want to scroll past it), so the earlier + 1 is needed to keep the math balanced.
In short: the + 1 compensates for the later - 1, making sure we always create one full blank line of space for the status bar/prompt and preventing the overlap when the terminal doesn’t have enough free lines left.
=> fix(tui): account for cursor position when determining the size

flake.nix
`meta.mainProgram` must be set otherwise `lib.getExe` assumes that the package name is `television` and home manager shell integrations are broken
=> fix(nix): set meta.mainProgram field

tests/cli/cli_input.rs, tests/cli/cli_ui.rs, tests/cli/cli_ui_behavior.rs
Fixes #631 
Added constraints to make either mitigate or remove "flakiness" for some tests
=> test(cli): fix some flaky tests, reinstate exact mode testing

.config/config.toml, television/channels/prototypes.rs, television/cli/args.rs, television/cli/mod.rs, television/config/mod.rs, television/config/ui.rs, television/draw.rs, television/main.rs, television/screen/input.rs, tests/cli/cli_ui.rs
- Allow users to specify a custom input prompt string via the `input_prompt` setting in the configuration file.
- Document the new `input_prompt` option in `.config/config.toml` with a commented example.
- Add a test to ensure that the input prompt is correctly loaded from the user configuration file.
=> feat(config): add support for custom input prompt in user config

television/utils/shell/completion.fish
fixes #653 
> https://github.com/alexpasmantier/television/blob/28f58e0641e3e4a56f02c39e165642024da430df/television/utils/shell/completion.fish#L112
> 
> This line should be
> 
> ```
> commandline -t -- (string escape -- "$dir$i")' '
> ```
> 
> This is a bug in the fish completion. Bash seems to be fine.
> 
> Testing with:
> 
> ```
> ❯ fish --version
> fish, version 4.0.2
> 
> ❯ mkdir -p "a/with whitespace"
> 
> ❯ cd a<ctrl-t>
> ```
> 
> Result:
> 
> ```
> ❯ cd a/'with whitespace/'
> ```
> 
> Expected result:
> 
> ```
> ❯ cd 'a/with whitespace/'
> ```
> 
> The fix on top gets this result.
=> fix(fish): more robust string escaping

website/src/components/HomepageFeatures/index.tsx, website/src/hooks/index.ts, website/src/hooks/useGenerateSiteUrl.ts
Currently the links on the docs homepage are broken, because when we run the website locally it uses [just a slash as the `prefix`/`baseUrl`, but when run as a production build it uses `/television` as the `baseUrl`](https://github.com/alexpasmantier/television/blob/1d6b996c834bf9b2ec7f1811e202c02b4507096c/website/docusaurus.config.ts#L21). So I added a hook that will take the `baseUrl` and append it to the link you provide. This hook should be used for any relative link that we add to the app in React (`.tsx`) files.
=> fix(website): Fixed broken links on home page

television/channels/entry.rs, television/channels/prototypes.rs, television/previewer/cache.rs, television/previewer/mod.rs, television/television.rs, television/utils/cache.rs
Fixes #660
**This PR adds a cache mechanism for previews that can be set on a per-channel basis.**
**Typical use case**: your preview is making an expensive call (e.g. API call, heavily computational, etc.)
This introduces a new `cache` option inside each channel's preview specification:
```toml
[metadata]
name = "test"
[source]
command = "echo 'test1\\ntest2\\ntest3\\ntest4\\ntest5'"
[preview]
command = "sleep 1 && echo 'Previewing {}'"
cached = true
```
=> feat(preview): previews can now be cached on a per-channel basis

.config/config.toml, television/action.rs, television/app.rs, television/cable.rs, television/channels/entry.rs, television/channels/prototypes.rs, television/channels/remote_control.rs, television/cli/mod.rs, television/config/keybindings.rs, television/config/mod.rs, television/config/shell_integration.rs, television/event.rs, television/keymap.rs, television/main.rs, television/screen/help_panel.rs, television/screen/keybindings.rs, television/screen/result_item.rs, television/screen/status_bar.rs, television/television.rs, tests/cli/cli_input.rs, tests/cli/cli_ui_behavior.rs, tests/subcommands.rs
**IMPORTANT** Due to the nature of the changes this is a backwards incompatible change
This PR reworks the already existing Action -> Bindings system in to a more scalable system using
- Keys -> Actions
- Events -> Actions
With the new system a key or event can execute one or more actions sequentially, for example
```toml
[keybindings]
"f1" = ["toggle_preview", "toggle_status_bar"]
```
Exposes input edit actions that we previously hard-coded
=> Binding foundation

benches/main/ui.rs, cable/unix/files.toml, docs/01-Users/07-channels.md, television/channels/channel.rs, television/channels/entry.rs, television/channels/prototypes.rs, television/channels/remote_control.rs, television/main.rs, television/screen/result_item.rs, television/utils/command.rs
Add the possibility to change the separator when multiple items are selected and we're executing and external action.
```toml
[actions.edit]
description = "Open selected files in editor"
command = "nvim {split:\\n:..|map:{append:'|prepend:'}|join: }"
mode = "execute"
separator = "\n"
```
Default value is the newline, but depending on the actual entries it might be beneficial to use another one
Add external actions documentation
Add support for common use case where we only want to escape every selection, allowing a short syntax like:
```toml
command = 'nvim {}'
```
=> feat: better handling external action's arguments

cable/unix/files.toml, docs/01-Users/07-channels.md, television/app.rs, television/channels/prototypes.rs, television/event.rs, television/main.rs, television/utils/command.rs
This improves support for `fork` and adds the logic for the `exec` feature.
I'm dropping the `OutputMode` logic for now as it doesn't seem that useful and kind of gets in the way right now. We might add that back later on.
=> feat(actions): improve actions behavior and add support for `exec`

docs/01-Users/01-installation.md
Add NetBSD install instructions
I've just packaged `television` for NetBSD and merged the package into pkgsrc main branch.
Commit log for reference, https://mail-index.netbsd.org/pkgsrc-changes/2025/08/07/msg328025.html
Could you please consider adding this to the supported platforms?
Thanks!
Regards
=> feat: add support for NetBSD installation

television/utils/shell/completion.zsh
use the $TTY var in the zsh integration so that the paste bracketing is disabled in the correct terminal.
See https://github.com/alexpasmantier/television/pull/512#pullrequestreview-3137810333
=> fix(shell): use $TTY for paste bracketing override
